### ISSUE TITLE
Problem with StaticFiles ...

### ISSUE THREAD

**Issue by ohmeow** [tiangolo/uvicorn-gunicorn-starlette-docker#10]
If I include this in my main.py
```
app.mount('/static', StaticFiles(directory='static')) 
```
Where `static` is a child folder of `app` locally, the following fails:

```
docker run -d --name myimage_c -p 3000:5000 -e PORT="5000" myimage
```

Even more interesting ... if I remove that line all together, static assents (images, javascript, css) get served from my /static folder just fine.

Any advice on what I should be doing to correctly setup my static files location with the docker image?  

Thanks

**Comment by tiangolo** [comment]
I assume you solved your problem, thanks for closing the issue :+1:
