### ISSUE TITLE
Is it safe to use this image for production?

### ISSUE THREAD

**Issue by fedecastelli** [tiangolo/uvicorn-gunicorn-starlette-docker#12]
I have to setup the server for the production environment and I'm using the FastAPI framework. The documentation of the framework suggests to use this docker image because it's ready and customizabile. So what I'll do is to expose my application using Gunicorn using the Uvicorn workers.

Is it safe? Because I was reading some articles and they suggest to put NGINX as a Reverse Proxy in front of Gunicorn. In this case, the request is received by NGINX and then it decides where to route it. I can't understand the differences. Thanks!

**Comment by fedecastelli** [comment]
I asked this question also in [Stackoverflow](https://stackoverflow.com/questions/59771332/is-it-safe-to-use-this-image-uvicorn-gunicorn-starlette-docker-for-production) and they answered me:

> The docker image is fine to use, but you should also put nginx in front of it. The main reason for doing this is to protect yourself against denial of service attacks as gunicorn offers little protection here.

Is there a chance you'll release this Dockerimage with NGINX as Proxy Server?

**Comment by tiangolo** [comment]
The type of attack that Nginx on top prevents from is https://en.wikipedia.org/wiki/Slowloris_(computer_security)

Starlette is a modern asynchronous framework, it doesn't use a single thread or process per request. It can handle a massive amount of concurrent requests, so there's no need for Nginx.

Gunicorn was made before these new frameworks existed, assuming WSGI frameworks like Flask or Django, which can only deal with one request per process or thread. But here Gunicorn is only used to start Uvicorn that then takes care of handling all that in an event loop.

So there's no need for Nginx.

If you still want to have a load balancer on top, you could add another container with Nginx (or Traefik) on top.
