### ISSUE TITLE
What is the role of each component in the proposed stack ?

### ISSUE THREAD

**Issue by kleysonr** [tiangolo/uvicorn-gunicorn-starlette-docker#20]
My question may be a little bit out of the topic, but this project looks interesting. I would like to understand it a little better.

I've been looking for some answers and clarifications about the integration among uvicorn/gunicorn/starlette and what is the role that each one play in the stack to delivery a high performance system.

May you please help on that, explaining what is the role of each component and how they help each other on a high performance stack ?

Best Regards.
Kleyson Rios.

**Comment by tiangolo** [comment]
Starlette is a Python web framework based on the ASGI spec. It needs an ASGI server to run the application built with Starlette. Uvicorn is a server that implements the ASGI spec. But Uvicorn by default would run in a single process. Gunicorn can start, control, and manage multiple processes.

Gunicorn is a full server using the old spec, WSGI. But it has the capability of using other workers and managing their processes. So Gunicorn can manage multiple Uvicorn workers (multiple processes) each running the web application built with Starlette.

**Comment by kleysonr** [comment]
@tiangolo but what is the difference between using Gunicorn to run multiple Uvicorn works and run uvicorn itself with the option **--workers X** ?

**Comment by tiangolo** [comment]
Gunicorn takes care of restarting workers if they die. Uvicorn doesn't do that. That's basically it. 🤷 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
