### ISSUE TITLE
Image/pyenv issue

### ISSUE THREAD

**Issue by bkbuilt** [tiangolo/uvicorn-gunicorn-starlette-docker#21]
I am building an application, starlette backend with vue frontend. I have utilized this to get the backend up and running with Docker. All the configurations, as far as I can tell, are proper. I have successfully built the image (traefik, app, db), even using docker-compose build --no-cache to ensure it was building with my most up to date requirements.txt and dev.txt. 

When I use docker-compose up, the db instance runs perfectly and the app does as well, except for an error that appears after it says the app is up and running on a localhost. It throws an error saying  
`File "./app/main.py", in line 6, in <module>
    from starlette.middleware.sessions import SessionMiddleware
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 5, in <module>
    import itsdangerous
  ModuleNotFoundError: No module named 'itsdangerous'`

I have ensured that the path is in pythonpath (in a .env), checked that itsdangerous is in the requirements.txt file which is ran during docker-compose build. I am working in a pyenv virtualenv, however it is checking local packages for this (I imagine it is because Docker works locally for this instance (not extremely familiar with Docker at its core).

Do you know any other possible way I could resolve this issue?

**Comment by petatemarvin26** [comment]
just install the library `itsdangerous`, here is the [Link][1]

[1]: https://pypi.org/project/itsdangerous/

**Comment by tiangolo** [comment]
Thanks for the help here @petatemarvin26  ! 👏  🙇 

If that solves the original problem, then you can close this issue @bkbuilt  ✔️

**Comment by bkbuilt** [comment]
@petatemarvin26 @tiangolo Wow I forgot I even created this issue lol was when I had just started a new job! I did end up resolving the problem at the time by installing itsdangerous. I forgot to come back and close the issue back then I'm sorry!

**Comment by fjbsantiago** [comment]
Starlette does no include all its dependencies by default.
Installing it with `pip install starlette[full]` solved a similar issue for me: https://github.com/encode/starlette/blob/master/pyproject.toml#L36
