### ISSUE TITLE
Add image for python 3.9

### ISSUE THREAD

**Issue by louisnow** [tiangolo/uvicorn-gunicorn-starlette-docker#24]
It's been a while since python3.9 has been released so it would be nice if the docker container was updated to use python3.9 and the latest starlette and uvicorn libraries

**Comment by tiangolo** [comment]
Yep, there's one. 🚀 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
