### ISSUE TITLE
Startup carries out a heavy import over again in each worker

### ISSUE THREAD

**Issue by adam-funk** [tiangolo/uvicorn-gunicorn-starlette-docker#25]
I'm trying to use this docker image to provide a REST service that does some calculations based on word embeddings, so I have a module file `analysis.py` (beside `main.py`) that loads the rather large embeddings data file. Obviously I only want that in memory once, so I was trying to take advantage of way Python normally imports a module only once. 

But when I run the docker image, it takes up a massive amount of memory because it is loading the data several times (once in each worker). Is there a way to prevent this?

**Comment by adam-funk** [comment]
Sorry! I figured out that gunicorn is doing this, so I'm looking through that documentation now.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
