### ISSUE TITLE
Application doesnt start

### ISSUE THREAD

**Issue by nicoughton** [tiangolo/uvicorn-gunicorn-starlette-docker#3]
Hi,

I suspect I am doing something stupid but I have tried both the sample app and converted one of my own apps to use Starlette and get the same result.

The docker image builds fine and seems to run but just sits with the message [Info] Waiting for Application startup

I am then unable to access my application

What am I doing wrong?!

Thanks

Nic

**Comment by nicoughton** [comment]
Ok - so I was right I was doing something stupid!

Wasn't mapping the port correctly in the docker run command

**Comment by tiangolo** [comment]
Sorry for the delay @nicoughton 

> Ok - so I was right I was doing something stupid!

That means you were programming, it's just "standard" for us all :smile: :man_shrugging: 

 I'm glad you solved your problem. Thanks for reporting back and closing the issue.

**Comment by peterdeme** [comment]
@nicoughton do you remember what's your issue? I can't get it running

**Comment by huanggengkeng** [comment]
i run the docker command  " docker run -p 80:8082 -e BIND="127.0.0.1:8082" --name snt_container snt_image"  but the result also same with the message [Info] Waiting for Application startup
