### ISSUE TITLE
Wrong URL for the dockerhub repository

### ISSUE THREAD

**Issue by skasch** [tiangolo/uvicorn-gunicorn-starlette-docker#7]
Hello,

In the README.md, the link to the dockerhub image is broken; the correct URL should be

```
https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-starlette
```

Instead of

```
https://hub.docker.com/r/tiangolo/uvicorn-starlette-gunicorn
```

(`gunicorn` and `starlette` are inverted)

**Comment by tiangolo** [comment]
Yep, you're right. I just fixed it. Thanks! :heavy_check_mark:
